logo: ./pic/logo.png
description: >
  This is a collaborative project between The Cooper Union Acoustic and vIBRATION laboratory and NYU Steinhardt MARL.
  This project presents a low-cost, high-quality first-order ambisonics (FOA) microphone based on low-noise MEMS systems.
  <br><br>

  <a href='https://raymondminglee.github.io/'>Back to homepage</a>

theme: jekyll-theme-minimal